name: Deploy
on:
  # workflow_dispatch: {}
  push:
    branches:
      - master
    # paths:
    #   - 'docs/**' # æŒ‡å®š docs ç›®å½•ä¸‹çš„æ–‡ä»¶å˜åŒ–æ—¶æ‰è§¦å‘
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      # pages: write
      # id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # - name: å®‰è£…pnpm
      #   uses: pnpm/action-setup@v2
      #   with:
      #     version: 8

      - uses: actions/setup-node@v3
        with:
          cache: npm # pnpm

      - name: å®‰è£… node ä¾èµ–
        run: npm i # pnpm i --frozen-lockfile

      - name: Build
        run: npm run docs-build # pnpm docs-build

      - name: Deploy to GitHub Pages ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4.4.2
        with:
          folder: blog/.vitepress/dist # The folder the action should deploy.
          # branch: master
          # token: ${{ secrets.DEPLOY }}
      # - uses: actions/configure-pages@master
      # - uses: actions/upload-pages-artifact@v1
      #   with:
      #     path: .vitepress/dist
      # - name: Deploy
      #   id: deployment
      #   uses: actions/deploy-pages@v1
